#!/usr/bin/env python3
"""
Export suspicious coverage summary to Markdown.

This script analyzes spec_coverage.csv and generates a summary report
of suspicious coverage entries (test_covered_any=TRUE but code_implemented=FALSE).

Output: docs/reports/validation_artifacts/suspicious_coverage/suspicious_summary.md
"""

import csv
from collections import defaultdict
from pathlib import Path


def load_suspicious_coverage(spec_coverage_path: Path) -> list[dict]:
    """
    Load all suspicious coverage entries from spec_coverage.csv.
    
    Returns list of row dicts where:
        test_covered_any == TRUE AND code_implemented == FALSE
    """
    suspicious = []
    
    with open(spec_coverage_path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            test_covered_any = row.get("test_covered_any", "").strip().upper()
            code_implemented = row.get("code_implemented", "").strip().upper()
            
            if test_covered_any == "TRUE" and code_implemented == "FALSE":
                suspicious.append(row)
    
    return suspicious


def compute_statistics(suspicious_rows: list[dict], total_rows: int) -> dict:
    """
    Compute summary statistics for suspicious coverage.
    
    Returns dict with:
        - count: total suspicious entries
        - percentage: suspicious / total
        - by_rule_type: counts grouped by rule_type
        - by_identifier_family: counts grouped by identifier_family
    """
    count = len(suspicious_rows)
    percentage = (count / total_rows * 100) if total_rows > 0 else 0.0
    
    by_rule_type = defaultdict(int)
    by_identifier_family = defaultdict(int)
    
    for row in suspicious_rows:
        rule_type = row.get("rule_type", "UNKNOWN").strip()
        identifier_family = row.get("identifier_family", "UNKNOWN").strip()
        
        by_rule_type[rule_type] += 1
        by_identifier_family[identifier_family] += 1
    
    return {
        "count": count,
        "percentage": percentage,
        "by_rule_type": dict(by_rule_type),
        "by_identifier_family": dict(by_identifier_family),
    }


def generate_markdown_report(stats: dict, suspicious_rows: list[dict]) -> str:
    """Generate Markdown report from statistics and suspicious rows."""
    lines = [
        "# Suspicious Coverage Summary",
        "",
        "**Generated**: Auto-generated by `tools/spec_coverage/export_suspicious_summary.py`",
        "",
        "## Overview",
        "",
        f"- **Total Suspicious Entries**: {stats['count']}",
        f"- **Percentage of Total Rules**: {stats['percentage']:.2f}%",
        "",
        "Suspicious coverage = `test_covered_any == TRUE` AND `code_implemented == FALSE`",
        "",
        "This indicates a mismatch where tests claim to cover a spec rule that is marked as not implemented.",
        "",
    ]
    
    # Grouped by rule_type
    lines.append("## Breakdown by Rule Type")
    lines.append("")
    
    if stats["by_rule_type"]:
        lines.append("| Rule Type | Count |")
        lines.append("|-----------|-------|")
        for rule_type, count in sorted(
            stats["by_rule_type"].items(),
            key=lambda x: (-x[1], x[0])
        ):
            lines.append(f"| {rule_type} | {count} |")
    else:
        lines.append("_No suspicious coverage found._")
    
    lines.append("")
    
    # Grouped by identifier_family
    lines.append("## Breakdown by Identifier Family")
    lines.append("")
    
    if stats["by_identifier_family"]:
        lines.append("| Identifier Family | Count |")
        lines.append("|-------------------|-------|")
        for identifier_family, count in sorted(
            stats["by_identifier_family"].items(),
            key=lambda x: (-x[1], x[0])
        ):
            lines.append(f"| {identifier_family} | {count} |")
    else:
        lines.append("_No suspicious coverage found._")
    
    lines.append("")
    
    # Detailed list
    if suspicious_rows:
        lines.append("## Detailed List")
        lines.append("")
        lines.append("| Rule ID | Identifier | Rule Type | Identifier Family |")
        lines.append("|---------|------------|-----------|-------------------|")
        
        for row in sorted(suspicious_rows, key=lambda r: r.get("rule_id", "")):
            rule_id = row.get("rule_id", "")
            identifier = row.get("identifier", "")
            rule_type = row.get("rule_type", "")
            identifier_family = row.get("identifier_family", "")
            
            lines.append(f"| {rule_id} | {identifier} | {rule_type} | {identifier_family} |")
        
        lines.append("")
    
    lines.append("---")
    lines.append("")
    lines.append("**Action Required**: Review these entries to determine if:")
    lines.append("1. Test coverage is incorrectly marked (should be FALSE)")
    lines.append("2. Implementation is incorrectly marked (should be TRUE)")
    lines.append("3. This is a genuine gap requiring implementation or test removal")
    lines.append("")
    
    return "\n".join(lines)


def main():
    """Main entry point."""
    # Paths
    project_root = Path(__file__).parent.parent.parent
    spec_coverage_path = project_root / "spec_coverage.csv"
    output_dir = project_root / "docs" / "reports" / "validation_artifacts" / "suspicious_coverage"
    output_path = output_dir / "suspicious_summary.md"
    
    # Ensure input exists
    if not spec_coverage_path.exists():
        print(f"❌ spec_coverage.csv not found at {spec_coverage_path}")
        return 1
    
    # Load data
    print(f"📊 Loading spec_coverage.csv from {spec_coverage_path}...")
    suspicious_rows = load_suspicious_coverage(spec_coverage_path)
    
    # Count total rows for percentage calculation
    with open(spec_coverage_path, "r", encoding="utf-8") as f:
        total_rows = sum(1 for _ in csv.DictReader(f))
    
    # Compute statistics
    stats = compute_statistics(suspicious_rows, total_rows)
    
    # Generate report
    print(f"📝 Generating report...")
    report = generate_markdown_report(stats, suspicious_rows)
    
    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")
    
    print(f"✅ Summary written to {output_path}")
    print(f"   Total suspicious entries: {stats['count']} ({stats['percentage']:.2f}%)")
    
    return 0


if __name__ == "__main__":
    exit(main())
