"""Integration / smoke tests against real station output files.

These tests load CSV outputs regenerated by the public single-station example
and validate data-correctness invariants:

1. No missing-value sentinels leak through — each column is checked
   against its own declared ``missing_values`` from FIELD_RULES
   (after applying scale factors).
2. Scale factors applied — values fall in physically plausible ranges.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import pytest

from noaa_spec.constants import (
    FIELD_RULES,
    is_quality_column,
    to_internal_column,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INTEGRATION_OUTPUT_DIR = PROJECT_ROOT / "tests" / "fixtures" / "integration_output"
CLEANED_FILENAME = "Cleaned.csv"


def _resolve_integration_output_dir() -> Path:
    configured = os.environ.get("NOAA_INTEGRATION_OUTPUT_DIR")
    if configured:
        return Path(configured).expanduser().resolve()
    return DEFAULT_INTEGRATION_OUTPUT_DIR


def _discover_station_dirs(output_dir: Path) -> list[Path]:
    if not output_dir.exists() or not output_dir.is_dir():
        return []
    return sorted(
        d
        for d in output_dir.iterdir()
        if d.is_dir() and (d / CLEANED_FILENAME).exists()
    )


OUTPUT_DIR = _resolve_integration_output_dir()

STATION_DIRS = _discover_station_dirs(OUTPUT_DIR)

# Guard: skip the whole module if no station outputs are present.
pytestmark = pytest.mark.skipif(
    len(STATION_DIRS) == 0,
    reason=(
        f"No station output directories found at {OUTPUT_DIR}. "
        "Set NOAA_INTEGRATION_OUTPUT_DIR to point at an integration fixture root."
    ),
)


# ── Helpers ──────────────────────────────────────────────────────────────


def _sentinel_set_for_column(col: str) -> set[float]:
    """Return the *scaled* sentinel values for *col* from FIELD_RULES.

    For a column like ``visibility_m`` the function looks up VIS →
    part 1 → ``missing_values`` and applies the part's ``scale`` so that
    the numbers are directly comparable to cleaned CSV values.
    If no rule is found an empty set is returned (nothing to check).
    """
    col = to_internal_column(col)
    # Parse "FIELD__partN" or "FIELD__value"  →  (field, part_index)
    parts = col.split("__", 1)
    if len(parts) != 2:
        return set()
    field = parts[0]
    suffix = parts[1]
    # Map suffix → numeric part index used in FIELD_RULES
    if suffix == "value":
        part_idx = 1
    elif suffix.startswith("part"):
        try:
            part_idx = int(suffix[4:])
        except ValueError:
            return set()
    else:
        return set()

    rule = FIELD_RULES.get(field)
    if rule is None:
        return set()
    pinfo = rule.parts.get(part_idx)
    if pinfo is None or not pinfo.missing_values:
        return set()
    scale = pinfo.scale or 1.0
    return {float(v) * scale for v in pinfo.missing_values}


def _value_columns(df: pd.DataFrame) -> list[str]:
    """Return numeric columns that carry measurement data."""
    return [
        c
        for c in df.select_dtypes(include="number").columns
        if not is_quality_column(c)
        and c not in {"ID", "Year", "MonthNum", "Hour", "Day", "YEAR"}
    ]


def _load(station: Path, name: str) -> pd.DataFrame:
    if name == "Cleaned":
        return pd.read_csv(station / CLEANED_FILENAME, low_memory=False)
    raise FileNotFoundError(f"No {name} CSV found for {station}")


# ── No sentinel leakage ─────────────────────────────────────────────────


class TestNoSentinelLeakage:
    """Sentinel values (999, 9999, …) must be NaN, not numbers."""

    @pytest.fixture(params=STATION_DIRS, ids=[d.name for d in STATION_DIRS])
    def station(self, request: pytest.FixtureRequest) -> Path:
        return request.param

    def test_cleaned_no_sentinels(self, station: Path):
        df = _load(station, "Cleaned")
        for col in _value_columns(df):
            sentinels = _sentinel_set_for_column(col)
            if not sentinels:
                continue
            vals = df[col].dropna()
            leaked = vals[vals.isin(sentinels)]
            assert leaked.empty, (
                f"{station.name} Cleaned: {col} has {len(leaked)} sentinel values "
                f"(sentinels={sentinels}, sample: {leaked.head().tolist()})"
            )


# ── Scale factors produce plausible ranges ──────────────────────────────


class TestPlausibleRanges:
    """Scaled fields must fall in physically reasonable ranges."""

    @pytest.fixture(params=STATION_DIRS, ids=[d.name for d in STATION_DIRS])
    def cleaned(self, request: pytest.FixtureRequest) -> pd.DataFrame:
        return _load(request.param, "Cleaned")

    def test_temperature_range(self, cleaned: pd.DataFrame):
        if "temperature_c" not in cleaned.columns:
            pytest.skip("TMP not present")
        vals = cleaned["temperature_c"].dropna()
        if vals.empty:
            pytest.skip("No TMP data")
        assert vals.min() >= -90, f"TMP too low: {vals.min()}"
        assert vals.max() <= 60, f"TMP too high: {vals.max()}"

    def test_dew_point_range(self, cleaned: pd.DataFrame):
        if "dew_point_c" not in cleaned.columns:
            pytest.skip("DEW not present")
        vals = cleaned["dew_point_c"].dropna()
        if vals.empty:
            pytest.skip("No DEW data")
        assert vals.min() >= -90, f"DEW too low: {vals.min()}"
        assert vals.max() <= 50, f"DEW too high: {vals.max()}"

    def test_wind_speed_range(self, cleaned: pd.DataFrame):
        if "wind_speed_ms" not in cleaned.columns:
            pytest.skip("WND speed not present")
        vals = cleaned["wind_speed_ms"].dropna()
        if vals.empty:
            pytest.skip("No WND speed data")
        # Scaled: m/s.  World record gust ~113 m/s.
        assert vals.min() >= 0, f"WND speed negative: {vals.min()}"
        assert vals.max() <= 120, f"WND speed too high (not scaled?): {vals.max()}"

    def test_wind_gust_range(self, cleaned: pd.DataFrame):
        if "wind_gust_ms" not in cleaned.columns:
            pytest.skip("OC1 not present")
        vals = cleaned["wind_gust_ms"].dropna()
        if vals.empty:
            pytest.skip("No OC1 data")
        assert vals.min() >= 0, f"OC1 negative: {vals.min()}"
        assert vals.max() <= 120, f"OC1 too high (not scaled?): {vals.max()}"

    def test_altimeter_pressure_range(self, cleaned: pd.DataFrame):
        if "altimeter_setting_hpa" not in cleaned.columns:
            pytest.skip("MA1 altimeter not present")
        vals = cleaned["altimeter_setting_hpa"].dropna()
        if vals.empty:
            pytest.skip("No MA1 altimeter data")
        # Reasonable altimeter settings: ~870–1085 hPa.
        assert vals.min() >= 850, f"MA1 altimeter too low: {vals.min()}"
        assert vals.max() <= 1100, f"MA1 altimeter too high (not scaled?): {vals.max()}"

    def test_sea_surface_temp_range(self, cleaned: pd.DataFrame):
        if "sea_surface_temperature_c" not in cleaned.columns:
            pytest.skip("SA1 not present")
        vals = cleaned["sea_surface_temperature_c"].dropna()
        if vals.empty:
            pytest.skip("No SA1 data")
        assert vals.min() >= -5, f"SA1 SST too low: {vals.min()}"
        assert vals.max() <= 45, f"SA1 SST too high (not scaled?): {vals.max()}"
