"""Integration / smoke tests against real station output files.

These tests load the CSV outputs regenerated by the pipeline for
the 10 sample stations and validate data-correctness invariants
from P0 and P1:

P0:
  1. No missing-value sentinels leak through — each column is checked
     against its own declared ``missing_values`` from FIELD_RULES
     (after applying scale factors).
  2. Scale factors applied — values fall in physically plausible ranges.
  3. Quality-flagged bad values are NaN, not numbers.

P1:
  4. Categorical and quality columns are absent from Monthly/Yearly.
  5. Field-appropriate aggregation (OC1 max, VIS min, TMP mean) produces
     values consistent with those functions.
"""

from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import pytest

from noaa_spec.constants import (
    FIELD_RULES,
    get_agg_func,
    is_categorical_column,
    is_quality_column,
    to_internal_column,
)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_INTEGRATION_OUTPUT_DIR = PROJECT_ROOT / "tests" / "fixtures" / "integration_output"


def _resolve_integration_output_dir() -> Path:
    configured = os.environ.get("NOAA_INTEGRATION_OUTPUT_DIR")
    if configured:
        return Path(configured).expanduser().resolve()
    return DEFAULT_INTEGRATION_OUTPUT_DIR


def _discover_station_dirs(output_dir: Path) -> list[Path]:
    if not output_dir.exists() or not output_dir.is_dir():
        return []
    return sorted(
        d
        for d in output_dir.iterdir()
        if d.is_dir() and (d / "LocationData_Yearly.csv").exists()
    )


OUTPUT_DIR = _resolve_integration_output_dir()

# All station directories that have the full five-file set.
STATION_DIRS = _discover_station_dirs(OUTPUT_DIR)

# Guard: skip the whole module if no station outputs are present.
pytestmark = pytest.mark.skipif(
    len(STATION_DIRS) == 0,
    reason=(
        f"No station output directories found at {OUTPUT_DIR}. "
        "Set NOAA_INTEGRATION_OUTPUT_DIR to point at an integration fixture root."
    ),
)


# ── Helpers ──────────────────────────────────────────────────────────────


def _sentinel_set_for_column(col: str) -> set[float]:
    """Return the *scaled* sentinel values for *col* from FIELD_RULES.

    For a column like ``visibility_m`` the function looks up VIS →
    part 1 → ``missing_values`` and applies the part's ``scale`` so that
    the numbers are directly comparable to cleaned CSV values.
    If no rule is found an empty set is returned (nothing to check).
    """
    col = to_internal_column(col)
    # Parse "FIELD__partN" or "FIELD__value"  →  (field, part_index)
    parts = col.split("__", 1)
    if len(parts) != 2:
        return set()
    field = parts[0]
    suffix = parts[1]
    # Map suffix → numeric part index used in FIELD_RULES
    if suffix == "value":
        part_idx = 1
    elif suffix.startswith("part"):
        try:
            part_idx = int(suffix[4:])
        except ValueError:
            return set()
    else:
        return set()

    rule = FIELD_RULES.get(field)
    if rule is None:
        return set()
    pinfo = rule.parts.get(part_idx)
    if pinfo is None or not pinfo.missing_values:
        return set()
    scale = pinfo.scale or 1.0
    return {float(v) * scale for v in pinfo.missing_values}


def _value_columns(df: pd.DataFrame) -> list[str]:
    """Return numeric columns that carry measurement data."""
    return [
        c
        for c in df.select_dtypes(include="number").columns
        if not is_quality_column(c)
        and c not in {"ID", "Year", "MonthNum", "Hour", "Day", "YEAR"}
    ]


def _load(station: Path, name: str) -> pd.DataFrame:
    return pd.read_csv(station / f"LocationData_{name}.csv")


# ── P0-1: No sentinel leakage ───────────────────────────────────────────


class TestNoSentinelLeakage:
    """Sentinel values (999, 9999, …) must be NaN, not numbers."""

    @pytest.fixture(params=STATION_DIRS, ids=[d.name for d in STATION_DIRS])
    def station(self, request: pytest.FixtureRequest) -> Path:
        return request.param

    def test_cleaned_no_sentinels(self, station: Path):
        df = _load(station, "Cleaned")
        for col in _value_columns(df):
            sentinels = _sentinel_set_for_column(col)
            if not sentinels:
                continue
            vals = df[col].dropna()
            leaked = vals[vals.isin(sentinels)]
            assert leaked.empty, (
                f"{station.name} Cleaned: {col} has {len(leaked)} sentinel values "
                f"(sentinels={sentinels}, sample: {leaked.head().tolist()})"
            )

    def test_yearly_no_sentinels(self, station: Path):
        df = _load(station, "Yearly")
        for col in _value_columns(df):
            sentinels = _sentinel_set_for_column(col)
            if not sentinels:
                continue
            vals = df[col].dropna()
            leaked = vals[vals.isin(sentinels)]
            assert leaked.empty, (
                f"{station.name} Yearly: {col} has {len(leaked)} sentinel values"
            )


# ── P0-2: Scale factors produce plausible ranges ────────────────────────


class TestPlausibleRanges:
    """Scaled fields must fall in physically reasonable ranges."""

    @pytest.fixture(params=STATION_DIRS, ids=[d.name for d in STATION_DIRS])
    def yearly(self, request: pytest.FixtureRequest) -> pd.DataFrame:
        return _load(request.param, "Yearly")

    def test_temperature_range(self, yearly: pd.DataFrame):
        if "temperature_c" not in yearly.columns:
            pytest.skip("TMP not present")
        vals = yearly["temperature_c"].dropna()
        if vals.empty:
            pytest.skip("No TMP data")
        assert vals.min() >= -90, f"TMP too low: {vals.min()}"
        assert vals.max() <= 60, f"TMP too high: {vals.max()}"

    def test_dew_point_range(self, yearly: pd.DataFrame):
        if "dew_point_c" not in yearly.columns:
            pytest.skip("DEW not present")
        vals = yearly["dew_point_c"].dropna()
        if vals.empty:
            pytest.skip("No DEW data")
        assert vals.min() >= -90, f"DEW too low: {vals.min()}"
        assert vals.max() <= 50, f"DEW too high: {vals.max()}"

    def test_wind_speed_range(self, yearly: pd.DataFrame):
        if "wind_speed_ms" not in yearly.columns:
            pytest.skip("WND speed not present")
        vals = yearly["wind_speed_ms"].dropna()
        if vals.empty:
            pytest.skip("No WND speed data")
        # Scaled: m/s.  World record gust ~113 m/s; yearly means << 100.
        assert vals.min() >= 0, f"WND speed negative: {vals.min()}"
        assert vals.max() <= 100, f"WND speed too high (not scaled?): {vals.max()}"

    def test_wind_gust_range(self, yearly: pd.DataFrame):
        if "wind_gust_ms" not in yearly.columns:
            pytest.skip("OC1 not present")
        vals = yearly["wind_gust_ms"].dropna()
        if vals.empty:
            pytest.skip("No OC1 data")
        assert vals.min() >= 0, f"OC1 negative: {vals.min()}"
        assert vals.max() <= 120, f"OC1 too high (not scaled?): {vals.max()}"

    def test_altimeter_pressure_range(self, yearly: pd.DataFrame):
        if "altimeter_setting_hpa" not in yearly.columns:
            pytest.skip("MA1 altimeter not present")
        vals = yearly["altimeter_setting_hpa"].dropna()
        if vals.empty:
            pytest.skip("No MA1 altimeter data")
        # Reasonable altimeter settings: ~870–1085 hPa.
        assert vals.min() >= 850, f"MA1 altimeter too low: {vals.min()}"
        assert vals.max() <= 1100, f"MA1 altimeter too high (not scaled?): {vals.max()}"

    def test_sea_surface_temp_range(self, yearly: pd.DataFrame):
        if "sea_surface_temperature_c" not in yearly.columns:
            pytest.skip("SA1 not present")
        vals = yearly["sea_surface_temperature_c"].dropna()
        if vals.empty:
            pytest.skip("No SA1 data")
        assert vals.min() >= -5, f"SA1 SST too low: {vals.min()}"
        assert vals.max() <= 45, f"SA1 SST too high (not scaled?): {vals.max()}"


# ── P1-1: Categorical / quality columns excluded from aggregated ─────


class TestCategoricalsExcluded:
    """Monthly and Yearly CSVs must not contain categorical or quality cols."""

    @pytest.fixture(params=STATION_DIRS, ids=[d.name for d in STATION_DIRS])
    def station(self, request: pytest.FixtureRequest) -> Path:
        return request.param

    _KNOWN_CATEGORICALS = {
        "present_weather_code_1",
        "present_weather_code_2",
        "present_weather_code_3",
        "present_weather_code_4",
        "past_weather_condition_code_1",
        "past_weather_condition_code_2",
        "past_weather_period_hours_1",
        "past_weather_period_hours_2",
        "wind_type_code",
        "ceiling_determination_code",
        "ceiling_cavok_code",
        "visibility_variability_code",
        "pressure_tendency_code",
        "convective_cloud_code",
    }

    def _check_no_categoricals(self, df: pd.DataFrame, label: str):
        present = self._KNOWN_CATEGORICALS & set(df.columns)
        assert not present, f"{label}: categorical columns still present: {present}"

    def _check_no_quality(self, df: pd.DataFrame, label: str):
        quality_cols = [c for c in df.columns if is_quality_column(c)]
        assert not quality_cols, f"{label}: quality columns still present: {quality_cols}"

    def test_yearly_no_categoricals(self, station: Path):
        df = _load(station, "Yearly")
        self._check_no_categoricals(df, f"{station.name}/Yearly")

    def test_yearly_no_quality(self, station: Path):
        df = _load(station, "Yearly")
        self._check_no_quality(df, f"{station.name}/Yearly")

    def test_monthly_no_categoricals(self, station: Path):
        df = _load(station, "Monthly")
        self._check_no_categoricals(df, f"{station.name}/Monthly")

    def test_monthly_no_quality(self, station: Path):
        df = _load(station, "Monthly")
        self._check_no_quality(df, f"{station.name}/Monthly")


# ── P1-2: Aggregation functions are correct ──────────────────────────────


class TestAggregationConsistency:
    """Yearly aggregated values must be consistent with the hourly source.

    We re-aggregate the Hourly CSV ourselves and compare against the
    pipeline's Yearly output to confirm the right function was used.
    """

    @pytest.fixture(params=STATION_DIRS, ids=[d.name for d in STATION_DIRS])
    def station(self, request: pytest.FixtureRequest) -> Path:
        return request.param

    def test_oc1_is_max_not_mean(self, station: Path):
        """OC1 (wind gust) yearly value should equal the max of hourly, not mean."""
        hourly = _load(station, "Hourly")
        yearly = _load(station, "Yearly")
        if "wind_gust_ms" not in hourly.columns or "wind_gust_ms" not in yearly.columns:
            pytest.skip("OC1 not present")
        if yearly["wind_gust_ms"].dropna().empty:
            pytest.skip("No OC1 yearly data")

        for _, yrow in yearly.iterrows():
            yr = yrow["Year"]
            h_vals = hourly.loc[hourly["Year"] == yr, "wind_gust_ms"].dropna()
            if h_vals.empty:
                continue
            expected_max = h_vals.max()
            expected_mean = h_vals.mean()
            actual = yrow["wind_gust_ms"]
            if pd.isna(actual):
                continue
            # The actual should be closer to max than to mean
            # (or equal to max, within float tolerance).
            assert actual == pytest.approx(expected_max, rel=1e-3), (
                f"{station.name} Year={yr}: OC1 yearly={actual:.2f}, "
                f"hourly max={expected_max:.2f}, hourly mean={expected_mean:.2f}"
            )

    def test_vis_is_min_not_mean(self, station: Path):
        """VIS (visibility) yearly value should equal the min of hourly, not mean."""
        hourly = _load(station, "Hourly")
        yearly = _load(station, "Yearly")
        if "visibility_m" not in hourly.columns or "visibility_m" not in yearly.columns:
            pytest.skip("VIS not present")
        if yearly["visibility_m"].dropna().empty:
            pytest.skip("No VIS yearly data")

        for _, yrow in yearly.iterrows():
            yr = yrow["Year"]
            h_vals = hourly.loc[hourly["Year"] == yr, "visibility_m"].dropna()
            if h_vals.empty:
                continue
            expected_min = h_vals.min()
            actual = yrow["visibility_m"]
            if pd.isna(actual):
                continue
            assert actual == pytest.approx(expected_min, rel=1e-3), (
                f"{station.name} Year={yr}: VIS yearly={actual:.2f}, "
                f"hourly min={expected_min:.2f}"
            )

    def test_tmp_is_mean(self, station: Path):
        """TMP (temperature) yearly value should equal the mean of hourly."""
        hourly = _load(station, "Hourly")
        yearly = _load(station, "Yearly")
        if "temperature_c" not in hourly.columns or "temperature_c" not in yearly.columns:
            pytest.skip("TMP not present")
        if yearly["temperature_c"].dropna().empty:
            pytest.skip("No TMP yearly data")

        for _, yrow in yearly.iterrows():
            yr = yrow["Year"]
            h_vals = hourly.loc[hourly["Year"] == yr, "temperature_c"].dropna()
            if h_vals.empty:
                continue
            expected_mean = h_vals.mean()
            actual = yrow["temperature_c"]
            if pd.isna(actual):
                continue
            assert actual == pytest.approx(expected_mean, rel=1e-3), (
                f"{station.name} Year={yr}: TMP yearly={actual:.4f}, "
                f"hourly mean={expected_mean:.4f}"
            )
