"""Deterministic PDF to Markdown conversion utilities."""

from __future__ import annotations

from pathlib import Path
import re
from unicodedata import normalize as unicode_normalize


_BLANK_LINE_RE = re.compile(r"\n{3,}")


def normalize_extracted_text(text: str) -> str:
    """Normalize PDF-extracted text into stable markdown-friendly text."""
    normalized = unicode_normalize("NFKC", text)
    normalized = normalized.replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in normalized.split("\n")]
    normalized = "\n".join(lines).strip()
    normalized = _BLANK_LINE_RE.sub("\n\n", normalized)
    return normalized


def render_markdown_document(
    page_texts: list[str],
    source_name: str,
    include_page_headers: bool = True,
) -> str:
    """Render normalized page text into a deterministic markdown document."""
    title = Path(source_name).name
    lines: list[str] = [f"# {title}", "", "_Generated by deterministic converter._", ""]

    for page_number, page_text in enumerate(page_texts, start=1):
        if include_page_headers:
            lines.extend([f"## Page {page_number}", ""])
        lines.append(page_text if page_text else "_[No extractable text on this page.]_")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def convert_pdf_to_markdown(
    input_pdf: Path,
    output_md: Path | None = None,
    include_page_headers: bool = True,
) -> Path:
    """Convert a PDF into markdown with deterministic, page-ordered output."""
    input_path = input_pdf.expanduser().resolve()
    if not input_path.exists() or not input_path.is_file():
        raise FileNotFoundError(f"Input PDF not found: {input_pdf}")

    target_path = (
        output_md.expanduser().resolve()
        if output_md is not None
        else input_path.with_suffix(".md")
    )
    target_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        from pypdf import PdfReader
    except ImportError as exc:  # pragma: no cover - defensive dependency error
        raise RuntimeError(
            "pypdf is required for pdf-to-markdown conversion. "
            "Install dependencies with 'poetry install'."
        ) from exc

    reader = PdfReader(str(input_path))
    page_texts = [
        normalize_extracted_text(page.extract_text() or "")
        for page in reader.pages
    ]

    markdown = render_markdown_document(
        page_texts,
        source_name=input_path.name,
        include_page_headers=include_page_headers,
    )
    target_path.write_text(markdown, encoding="utf-8", newline="\n")
    return target_path
